# MySQL.  Versions 4.1 and 5.0 are recommended.
#
#
# Be sure to use new-style password hashing:
#   http://dev.mysql.com/doc/refman/5.0/en/old-client.html
development:
  adapter: postgresql
  encoding: utf8
  database: diary_development
  username: postgres
  password: 123
  template: template1

test:
  adapter: postgresql
  encoding: utf8
  database: diary_test
  username: postgres
  password: 123
  template: template1

production:
  adapter: postgresql
  encoding: utf8
  database: diary_production
  username: postgres
  password: 123
  template: template1