module ApplicationHelper


  def select_country
    [
      ['Andorra','Andorra'],
      ['Afghanistan','Afghanistan'],
      ['Anguilla','Anguilla'],
      ['Albania','Albania'],
      ['Armenia','Armenia'],
      ['Angola','Angola'],
      ['Antarctica','Antarctica'],
      ['Argentina','Argentina'],
      ['Austria','Austria'],
      ['Australia','Australia'],
      ['Aruba','Aruba'],
      ['Azerbaijan','Azerbaijan'],
      ['Barbados','Barbados'],
      ['Bangladesh','Bangladesh'],
      ['Belgium','Belgium'],
      ['Burkina Faso','Burkina Faso'],
      ['Bulgaria','Bulgaria'],
      ['Bahrain','Bahrain'],
      ['Burundi','Burundi'],
      ['Benin','Benin'],
      ['Saint Barthélemy','Saint Barthélemy'],
      ['Bermuda','Bermuda'],
      ['Brunei','Brunei'],
      ['Bolivia','Bolivia'],
      ['British Antarctic Territory','British Antarctic Territory'],
      ['Brazil','Brazil'],
      ['Bahamas','Bahamas'],
      ['Bhutan','Bhutan'],
      ['Bouvet Island','Bouvet Island'],
      ['Botswana','Botswana'],
      ['Belarus','Belarus'],
      ['Belize','Belize'],
      ['Canada','Canada'],
      ['Cocos [Keeling] Islands','Cocos [Keeling] Islands'],
      ['Congo - Kinshasa','Congo - Kinshasa'],
      ['Cook Islands','Cook Islands'],
      ['Chile','Chile'],
      ['Cameroon','Cameroon'],
      ['China','China'],
      ['Colombia','Colombia'],
      ['Cuba','Cuba'],
      ['Christmas Island','Christmas Island'],
      ['Cyprus','Cyprus'],
      ['Czech Republic','Czech Republic'],
      ['East Germany','East Germany'],
      ['Germany','Germany'],
      ['Diego Garcia','Diego Garcia'],
      ['Djibouti','Djibouti'],
      ['Denmark','Denmark'],
      ['Dominica','Dominica'],
      ['Dominican Republic','Dominican Republic'],
      ['Algeria','Algeria'],
      ['Ecuador','Ecuador'],
      ['Estonia','Estonia'],
      ['Egypt','Egypt'],
      ['Eritrea','Eritrea'],
      ['Ethiopia','Ethiopia'],
      ['Spain','Spain'],
      ['Finland','Finland'],
      ['Fiji','Fiji'],
      ['Falkland Islands','Falkland Islands'],
      ['Micronesia','Micronesia'],
      ['France','France'],
      ['Gabon','Gabon'],
      ['United Kingdom','United Kingdom'],
      ['Grenada','Grenada'],
      ['Georgia','Georgia'],
      ['Ghana','Ghana'],
      ['Gibraltar','Gibraltar'],
      ['Gambia','Gambia'],
      ['Greece','Greece'],
      ['Guyana','Guyana'],
      ['Hong Kong SAR China','Hong Kong SAR China'],
      ['Hungary','Hungary'],
      ['Haiti','Haiti'],
      ['Indonesia','Indonesia'],
      ['Ireland','Ireland'],
      ['Israel','Israel'],
      ['Iraq','Iraq'],
      ['Iran','Iran'],
      ['Italy','Italy'],
      ['India','India'],
      ['Jamaica','Jamaica'],
      ['Jordan','Jordan'],
      ['Japan','Japan'],
      ['Kuwait','Kuwait'],
      ['Sri Lanka','Sri Lanka'],
      ['Libya','Libya'],
      ['Maldives','Maldives'],
      ['Mexico','Mexico'],
      ['Malaysia','Malaysia'],
      ['Netherlands','Netherlands'],
      ['Norway','Norway'],
      ['New Zealand','New Zealand'],
      ['Pakistan','Pakistan'],
      ['Philippines','Philippines'],
      ['Portugal','Portugal'],
      ['Palau','Palau'],
      ['Paraguay','Paraguay'],
      ['Qatar','Qatar'],
      ['Outlying Oceania','Outlying Oceania'],
      ['Romania','Romania'],
      ['Serbia','Serbia'],
      ['Russia','Russia'],
      ['Saudi Arabia','Saudi Arabia'],
      ['Seychelles','Seychelles'],
      ['Singapore','Singapore'],
      ['Sweden','Sweden'],
      ['Sudan','Sudan'],
      ['Slovakia','Slovakia'],
      ['Thailand','Thailand'],
      ['Tajikistan','Tajikistan'],
      ['Turkmenistan','Turkmenistan'],
      ['Turkey','Turkey'],
      ['Taiwan','Taiwan'],
      ['Ukraine','Ukraine'],
      ['United States','United States'],
      ['Uzbekistan','Uzbekistan'],
      ['Uganda','Uganda'],
      ['Vietnam','Vietnam'],
      ['Vanuatu','Vanuatu'],
      ['Yemen','Yemen'],
      ['South Africa','South Africa'],
      ['Zambia','Zambia'],
      ['Zimbabwe','Zimbabwe']

    ]
  end

end
